import { Providers } from '@/providers';
import type { Metadata } from 'next';
import { Delius, Geist, Geist_Mono, Nunito, Tiro_Devanagari_Marathi } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    display: 'swap',
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
    display: 'swap',
});

const nunito = Nunito({
    variable: '--font-nunito',
    subsets: ['latin'],
    display: 'swap',
});

const delius = Delius({
    weight: '400',
    variable: '--font-delius-family',
    subsets: ['latin'],
    display: 'swap',
});

const tiroDevanagariMarathi = Tiro_Devanagari_Marathi({
    weight: '400',
    variable: '--font-tiro-devanagari-marathi',
    subsets: ['latin', 'devanagari'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body
                suppressHydrationWarning
                className={`${geistSans.variable} ${geistMono.variable} ${nunito.variable} ${delius.variable} ${tiroDevanagariMarathi.variable} min-h-screen bg-background font-sans antialiased`}
            >
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
